### ISSUE TITLE
IllegalArgumentException caused by CartMechanismBlocks.findByRail

### ISSUE THREAD

**Issue by kikelkik** [EngineHub/CraftBook#1197]
The following error appears apparently in the server log. It should have got something to do with Minecarts.

Error: https://pastebin.com/STtJN6um

https://github.com/EngineHub/CraftBook/blob/69139adc4e7d94a114f505e9b5fa55bc8ea7bc80/src/main/java/com/sk89q/craftbook/mechanics/minecart/blocks/CartMechanismBlocks.java#L90

mechanisms.yml: [mechanisms.txt](https://github.com/EngineHub/CraftBook/files/4575045/mechanisms.txt)
CraftBook version: 3.10.2-SNAPSHOT;4586-0c3ad1c
Server version: git-Paper-240 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by me4502** [comment]
That looks like a Spigot bug? We're calling the API and for some reason it's looking up a null property

**Comment by kikelkik** [comment]
You mean because `test.getOppositeFace()` and `vine` can never be null (if it's the case..) ?

**Comment by me4502** [comment]
The error is occurring inside the vine.hasFace call, if vine was null the error would be different and test.getOppositeFace() cannot be null

**Comment by kikelkik** [comment]
I referenced to this issue in https://hub.spigotmc.org/jira/browse/SPIGOT-5716

**Comment by kikelkik** [comment]
Black Hole commented the ticket:
> Vine extends MultipleFacing. That interface declares a method getAllowedFaces to check if a face is supported. Vine supports all faces except DOWN.

So this: 
https://github.com/EngineHub/CraftBook/blob/69139adc4e7d94a114f505e9b5fa55bc8ea7bc80/src/main/java/com/sk89q/craftbook/mechanics/minecart/blocks/CartMechanismBlocks.java#L89

should be instead:
`for(BlockFace test : vine.getAllowedFaces()) {` 

Could you change it?

**Comment by me4502** [comment]
That method in Spigot must’ve changed then. It used to return false for down rather than erroring.

Realistically the error is still a spigot bug, but I’ll fix it within CraftBook when I get a chance

**Comment by me4502** [comment]
Fixed

**Comment by TheoRetisch1** [comment]
The system is still not working. As soon as you drive a minecart into a ladder, an error in the log occurs and nothing happens. 
Error: https://pastebin.com/pTiYr3DN
CraftBook version 3.10.2-SNAPSHOT;4597-90668cb
WorldGuard version 7.0.3-SNAPSHOT;2036-47cd96a
Paper 1.15.2 - 264

**Comment by me4502** [comment]
What is the setup of that ingame? That error indicates that for some reason a ladder doesn’t have a direction, which should never be possible

**Comment by TheoRetisch1** [comment]
The setup looks like this:
![2020-05-09_10 34 43](https://user-images.githubusercontent.com/24480321/81468656-2dc86b80-91e1-11ea-839c-6822f487a920.png)
I have also manually updated the ladders. It worked in version 1.13  using a 
older Craftbook version. Since the update to the latest Paper and Craftbook version it does not work anymore. So the ingame setup itself should not be the problem.

**Comment by me4502** [comment]
I cannot reproduce this issue, it's working fine for me - and I can't seem to setup a circumstance where Spigot says that a ladder does not have a direction, that's the main reason I was asking about ingame setup.

What direction are those ladders facing?

**Comment by TheoRetisch1** [comment]
Oh you`re right, it's about directions. It only happens with ladders facing north, all other directions work :)

**Comment by me4502** [comment]
I couldn't reproduce it, so I updated to the latest Paper version. Now ladders facing north have no direction according to the Spigot API 😦 

I'll look into if this is able to be worked around from within CraftBook, but if not it'll need to be reported to Spigot to see if they fix it. Tbh either way it should be reported, but I'll try finding a workaround anyway.

**Comment by kikelkik** [comment]
btw: the paper API doc has been updated with the fact that vines cannot face downwards.
solved in https://hub.spigotmc.org/jira/browse/SPIGOT-5716

if you give us  an exact description where in the spigot api ladders have no facing north direction (classname, method, (line)), we could forward that request to spigot. 
But of course you can also write that ticket there :)

**Comment by me4502** [comment]
I've just pushed a change that makes CraftBook use the reversed facing direction, rather than the direction that the ladder is attached to. This doesn't appear to have the same north = null bug.

I haven't looked deep into Spigot to find where it's broken, so I can't easily link code etc.

As for the previous issue, yeah I saw that Spigot have added a better error message. They should've done that when they changed behaviour in the first place ;)
